version: "1.0"
services:
  bot-service:
    image: bot-service:1.0
    container_name: bot-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    environment:
      HOST: 0.0.0.0
    volumes:
      - .:/home/node/botservices
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
    restart: on-failure:3
